INSERT INTO users (name, age) VALUES ("Alex", 26);
INSERT INTO users (name, age) VALUES ("Charlie", 27);
INSERT INTO users (name, age) VALUES ("Anna", 24);
INSERT INTO users (name, age) VALUES ("Maria", 51);
INSERT INTO users (name, age) VALUES ("Abby", 50);
INSERT INTO users (name, age) VALUES ("Billy", 85);
INSERT INTO users (name, age) VALUES ("Jim", 49);
INSERT INTO users (name, age) VALUES ("Bob", 45);
INSERT INTO users (name, age) VALUES ("Chris", 38);
INSERT INTO users (name, age) VALUES ("Ali", 84);
INSERT INTO users (name, age) VALUES ("Casey", 27);
INSERT INTO users (name, age) VALUES ("Kayla", 27);
INSERT INTO users (name, age) VALUES ("John", 27);
INSERT INTO users (name, age) VALUES ("Marcus", 26);
INSERT INTO users (name, age) VALUES ("Alaina", 27);
INSERT INTO users (name, age) VALUES ("Jeon", 24);
INSERT INTO users (name, age) VALUES ("Kyle", 31);
INSERT INTO users (name, age) VALUES ("Gilly", 32);
INSERT INTO users (name, age) VALUES ("Dave", 19);
INSERT INTO users (name, age) VALUES ("Magnus", 22);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Budjet planning", "Finance", 100, "6/30/30", "12/09/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Dog walking", "Exercise", 200, "4/26/20", "5/16/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Clean up", "Cleaning", 50, "12/30/20", "01/20/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Stop homelessness", "Charity", 3000, "7/12/20", "4/13/22");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Bake a cake", "Baking", 20, "4/01/20", "5/01/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Jewellery making", "Recreational", 30, "7/11/20", "7/12/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Study sessions", "Education", 200, "4/20/20", "7/20/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cure cancer", "Science", 40000, "4/20/20", "4/20/29");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Park run", "Events", 500, "5/17/20", "5/17/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Counseling", "Health care", 5000, "5/17/20", "5/17/21");

INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 13, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 15, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 18, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 20, 1);